Develop
appdevdesigns/appbuilder_class_core pull request #27
Opened 2021-05-25 08:58 UTC by jamesduncan

2021-06-09 04:01 UTC, Hiro-Nakamura requested changes

2021-06-10 07:44 UTC, jamesduncan commented on views/ABViewCarouselCore.js
> +      if (typeof this.settings.width != "undefined") {
I really like this...we are going to need it for most all of the fields...should we do it now or as a separate pull request later?

2021-06-10 07:46 UTC, jamesduncan commented on ABDataCollectionCore.js
> +               delete this.reloadTimer;
Yes...that is right...good catch. I will fix it.

2021-06-10 08:58 UTC, jamesduncan commented on ABDataCollectionCore.js
> +               delete this.reloadTimer;
Okay I have changed the three spots that we were doing it that way.

2021-06-10 09:12 UTC, merged